# Generated by Django 3.0.5 on 2020-05-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
