# Generated by Django 3.0.5 on 2020-05-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_delete_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='authors',
        ),
    ]
